### ISSUE TITLE
Babel-cli watch mode

### ISSUE THREAD

**Issue by kevinsimper** [michalkvasnicak/babel-plugin-css-modules-transform#27]
I tried using this together with the babel-cli and it does only extract the CSS when it is run the first time, every later change is not picked up even though babel does transpile the .js files.

I did try enable the `devMode` but it did not work.

**Comment by michalkvasnicak** [comment]
@kevinsimper I will look into it but I don't have enough free time these days. :-/

**Comment by michalkvasnicak** [comment]
@kevinsimper this is probably problem with `babel-cli` which watches for changes only in `javascript` files. So it is not aware that css file has changed. In the atom editor, you can trigger change by saving javascript file but in IDE like the Jetbrains Webstorm this will not cause an update because this IDE saves file only if is its content is really changed.

Unfortunately I can't find a way how to force babel-cli to retranspile javascript file according to css file change.

**Comment by michalkvasnicak** [comment]
Babel is not following imports / requires. Only way to trigger css update is to update javascript file which is importing it.

Unfortunately this plugin is not intended to extract css nor to substitute webpack. It should be used with webpack (which watches imports / required).

**Comment by kevinsimper** [comment]
@michalkvasnicak Okay, that is a bit annoying that babel-cli doesn't do that.

The problem with webpack is that on the server-side there is no need to bundle them all together, but it seems I have to do that if I want to import css.

**Comment by michalkvasnicak** [comment]
@kevinsimper You need webpack only for development purposes. But you can benefit from compiled server side javascript too. It can increase the performance of a server side application by bundling everything except system libraries to one file. This will eliminate file system usage in `require` calls.

We are using this at work for our siteproject. I created an application [(create-js-app)](https://github.com/michalkvasnicak/create-js-app) for that to simplify bootstraping of new projects and development. It is highly influenced by [create-react-app](https://github.com/facebookincubator/create-react-app) but is not dedicated only for react development. 

There is an universal plugin + simple universal template but you can create your own plugins for your project or technologies. But this package is still under development because it was created as a tool to satisfy need in my company. Feel free to ask anything if you are interested.

**Comment by pronebird** [comment]
CSS remains the same even if I change corresponding JS file.

**Comment by michalkvasnicak** [comment]
@pronebird do you have `devMode` enabled?

**Comment by pronebird** [comment]
@michalkvasnicak I must have missed something but it works with `devMode` on. I swear I tried it before...

**Comment by pronebird** [comment]
@michalkvasnicak after testing for a little while. Sometimes it happens that it does not refresh combined CSS. This is followed by:

>(node:17352) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 before-quit listeners added. Use emitter.setMaxListeners() to increase limit

Not sure what's going on there..

**Comment by Undistraction** [comment]
I have the same problem. CSS is only compiled on first run. Not when I edit the CSS and not when I edit the JS.
```
babel src --watch --out-dir lib
```
And
```
{
  "presets": [
    "react",
    [
      "env", {
      "targets": {
        "browsers": ["last 2 versions"]
      }
    }],
  ],
  "plugins": [
    ["css-modules-transform",
      {
        "extractCss": {
          "dir": "./lib/",
          "relativeRoot": "./src/",
          "filename": "[path]/[name].css"
        },
        "devMode": true,
      }
    ],
    "transform-object-rest-spread"
  ],
}
```

**Comment by michalkvasnicak** [comment]
@Undistraction yeah @pronebird tried to resolve this in #34 but it is a bit harder than that because we need to rewrite whole css file on every change. This can cause performance problems if CSS is big.

**Comment by Undistraction** [comment]
I'm trying to get away with using this in place of a much heavier Webpack config, but looks like I'll have to go down that route. Thanks though.

**Comment by michalkvasnicak** [comment]
@Undistraction resolved in #38 . You can install it using `next` version to try it. It does not watch the css files but regenerates whole css if you change corrensponding javascript file.

**Comment by Undistraction** [comment]
Brilliant. Thanks

**Comment by michalkvasnicak** [comment]
@Undistraction don't forget to set `devMode` to `true`. And please it would be really helpful if you try it and checks if everything work as expected so I can merge the PR.

**Comment by Undistraction** [comment]
I ended up building with Webpack because of this issue, but will try and
look on Monday.

**Comment by michalkvasnicak** [comment]
Released as `1.2.6` but is not tested properly so bugs can occur.

**Comment by pronebird** [comment]
@michalkvasnicak I tested it and it works fine. Thanks for this release! 🎉 

Important that it won't work with `--skip-initial-build` since `babel-plugin-css-modules-transform` needs to scan all sources with CSS imports to find all available CSS classes. 

This is currently a major blocker for me to adopt this babel plugin.

**Comment by michalkvasnicak** [comment]
@pronebird I see. In this case I cannot do anything to improve because `--skip-initial-build` is basically telling `babel` to not do anything so this plugin is not used until next build.
