### ISSUE TITLE
How to add PostCSS ?

### ISSUE THREAD

**Issue by nahue** [michalkvasnicak/babel-plugin-css-modules-transform#42]
Seems like css-modules-require-hook has a `use` config that allows to pass a array of postcss plugins, but this doesnt seem to work here.

Any ideas?

**Comment by michalkvasnicak** [comment]
Thank you. Could you send me an error message or something so I can track down the problem? Because `use` is accepting an array of functions or modules exporting a functions see [use option resolver](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform/blob/master/src/options_resolvers/use.js)

**Comment by nahue** [comment]
Oh im sorry i fixed it with 
`"append": [
	"postcss-cssnext"
],`

`use` was working but somehow messed up css modules (im using it with next.js), but `append` works like a charm!

**Comment by michalkvasnicak** [comment]
So is it ok now? 🙂  Can I close this issue? `append` and `use` basically have the same code.

**Comment by nahue** [comment]
yes please! and sorry!
