### ISSUE TITLE
Using this plugin for Library with extractCSS option

### ISSUE THREAD

**Issue by jvenki** [michalkvasnicak/babel-plugin-css-modules-transform#57]
I am creating a library and each component will import its respective CSS which needs to be CSS-Modularized. 

I am also using the following config in .babelrc

```
                [
                    "css-modules-transform", 
                    {
                        "preprocessCss": "./config/babel-sass-loader.js",
                        "generateScopedName": "[name]_[local]_[hash:base64:5]",
                        "extensions": [".css", ".scss"],
                        "ignore": "*/styles/*",
                        "extractCss": {
                            "dir": "./dist/",
                            "relativeRoot": "./src/",
                            "filename": "[path]/[name].scss"
                        }                
                    }
                ]
```

After running babel-cli, I see that the CSS files are having scoped names and the JS file also has the mapping between **original name** to **scoped name**. However, the generated JS doesnt have the import anymore to the processed CSS file. This is because of the line https://github.com/michalkvasnicak/babel-plugin-css-modules-transform/blob/master/src/index.js#L152. 

Without this link through import, the consumers of this library doesnt get the CSS definitions. Am I missing some config?

**Comment by michalkvasnicak** [comment]
Hello, this library is intended to be used in projects that are importing css for server side render. That means that imports/requires will be replaces by objects where keys are a css class names. If you're not using webpack to compile client side JS (webpack will automatically do the same as this plugin but it will append css files to assets, so it can automatically link them for you). 

What you can do is link your css files in HTML using `<link />` or import them in a project so webpack will add them to the assets.

I can't keep import/require to css files in a code because it doesn't make any sense. This plugin doesn't handle linking css files in HTML and if you keep imports/requires to css files, it'll fail in node.js unless you are using `css-modules-require-hook` because css are not valid js modules.
